### ISSUE TITLE
hexdump file not updated when binary changes

### ISSUE THREAD

**Issue by watersne** [stef-levesque/vscode-hexdump#66]
Extension Version 1.7.2, VS Code Version: 1.38.1. OS: Linux

The hexdump seems to rely on some cached version of the binary, or cache the .hexdump file somewhere. As I make changes to the binary they aren't reflected in the hexdump.

Steps:
1. Generate a binary
2. Show the hexdump of the binary
3. Close the hexdump of the binary
4. Change the source and regenerate the binary
5. Show the hexdump. The hexdump remains unchanged from before, but the binary has changed.

**Comment by joeywang4** [comment]
I think I have solved this issue.
You can try it out at #67.

**Comment by unl1ght** [comment]
Will this fix be applied to the current VS Code extension soon?

**Comment by leohoe** [comment]
I'm running into the same issue. 
The current VS Code extension still does not update the hexdump when the file changes.

**Comment by filipux** [comment]
I'm seeing this problem on macOS too

**Comment by iliazeus** [comment]
@watersne, I resolved this issue in my fork: https://github.com/iliazeus/vscode-hexdump.

The fix was to simply invalidate the cache when a corresponding hexdump is closed.

[Marketplace link](https://marketplace.visualstudio.com/items?itemName=iliazeus.vscode-hexdump)

**Comment by stef-levesque** [comment]
Fixed in version 1.8.0

**Comment by Niko-O** [comment]
I have version 1.8.1 installed and this still happens.
VS Code version is 1.51.1

**Comment by Jed-Z** [comment]
I encountered the same problem in 'Remote - WSL'. Hexdump results won't change when the binary changes, unless I reload the window.

hexdump for VSCode v1.8.1
VS Code Version 1.55.2 on Windows

**Comment by jiisamitt** [comment]
i recommend using another viewer like hex editor, that worked for me
